version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.prod
    env_file: .env.prod
    environment:
      # Railway define $PORT automaticamente; local usamos 8080.
      - PORT=8080
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.prod
    env_file: .env.prod
    environment:
      # IMPORTANTE: se for testar local, aponte para o backend local
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped