import { MD3LightTheme as DefaultTheme } from 'react-native-paper';
import { Colors } from './Colors';

export const theme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    primary: Colors.primary,
    onPrimary: '#ffffff',
    primaryContainer: '#dbeafe',
    onPrimaryContainer: '#1e3a8a',
    secondary: Colors.secondary,
    onSecondary: '#ffffff',
    secondaryContainer: '#f1f5f9',
    onSecondaryContainer: '#334155',
    tertiary: Colors.info,
    onTertiary: '#ffffff',
    tertiaryContainer: '#eff6ff',
    onTertiaryContainer: '#1e40af',
    error: Colors.error,
    onError: '#ffffff',
    errorContainer: '#fef2f2',
    onErrorContainer: '#7f1d1d',
    background: Colors.background,
    onBackground: Colors.text,
    surface: Colors.cardBackground,
    onSurface: Colors.text,
    surfaceVariant: Colors.backgroundSecondary,
    onSurfaceVariant: Colors.textSecondary,
    outline: Colors.border,
    outlineVariant: Colors.borderMuted,
    shadow: Colors.cardShadow,
    scrim: 'rgba(0, 0, 0, 0.5)',
    inverseSurface: Colors.text,
    inverseOnSurface: Colors.background,
    inversePrimary: '#60a5fa',
    elevation: {
      level0: 'transparent',
      level1: '#ffffff',
      level2: '#f8fafc',
      level3: '#f1f5f9',
      level4: '#e2e8f0',
      level5: '#cbd5e1',
    },
    surfaceDisabled: 'rgba(28, 27, 31, 0.12)',
    onSurfaceDisabled: 'rgba(28, 27, 31, 0.38)',
    backdrop: 'rgba(49, 47, 51, 0.4)',
  },
};