[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python -m gunicorn --bind 0.0.0.0:$PORT --workers 4 --timeout 120 --preload app:app"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production.variables]
NODE_ENV = "production"
FLASK_ENV = "production" 
DEBUG = "false"

[environments.production.build]
buildCommand = "pip install -r requirements.txt && python -m alembic upgrade head"

[service]
name = "fisioflow-backend"